name: Version dispatcher
on:
  push:
    tags:
    - v.*
    
env:
  CORRECT_TAG: 0
  DEPLOY_TARGET: "nMagic/test-ci-deploy"
  DEPLOY_WORKFLOW: "change_version.yml"
  DEPLOY_BRANCH: "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag
        run: |
          if [[ "${{ github.ref }}" =~ ^refs\/tags\/v\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; 
          then
            echo "CORRECT_TAG=1" >> $GITHUB_ENV
          fi

      - name: Dispatch deploy trigger
        if: ${{ env.CORRECT_TAG == 1 }}
        run: |
          VERSION=echo "${{ github.ref }}" | grep -oP "v\.[0-9]+\.[0-9]+\.[0-9]+"
          echo $VERSION
          DATA='{"ref":"${{ env.DEPLOY_BRANCH }}","inputs":{"app":"ANFISA_FRONTEND_VERSION","version":"$VERSION")"}}';
          echo $DATA;
          curl -v \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.DEPLOY_TOKEN }}" \
          https://api.github.com/repos/$DEPLOY_TARGET/actions/workflows/$DEPLOY_WORKFLOW/dispatches \
          -d '$DATA'
