name: Version dispatcher
on:
  push:
    branches:
    - main
    tags:
    - v.*
    
env:
  CORRECT_PUSH: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check branch
        if: contains(github.ref, 'heads')
        run: |
          if [ $(git rev-list -n 1 ${{ github.ref }} | git tag --contains | grep -E "v\.[0-9]+\.[0-9]+\.[0-9]+") == "" ]; then
            echo "CORRECT_PUSH=0" >> $GITHUB_ENV
          else
            echo "CORRECT_PUSH=1" >> $GITHUB_ENV
          fi

      - name: Extract branch name
        if: contains(github.ref, 'tags')
        run: echo "::set-output name=branch::$(git rev-list -n 1 ${{ github.ref }} | git branch --contains)"
        id: extract_branch

      - name: Check tag
        if: contains(github.ref, 'tags') && contains(steps.extract_branch.outputs.branch, 'main')
        run: echo "CORRECT_PUSH=1" >> $GITHUB_ENV

      - name: Test
        if: ${{ env.CORRECT_PUSH == 1 }}
        run: echo Hooray
