name: Version dispatcher
on:
  push:
    branches: 
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: echo "::set-output name=branch::$(git rev-list -n 1 ${{ github.ref }} | git branch --contains)"
        id: branch

      - name: test
        if: contains(steps.branch.outputs.branch, 'main') == true
        run: echo yikes

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
