name: Version dispatcher
on:
  push:
    tags:
    - v.*
    
env:
  CORRECT_TAG: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check tag
        run: |
          if [[ "${{ github.ref }}" =~ refs\/tags\/v\.[0-9]+\.[0-9]+\.[0-9]+ ]]; 
          then
            echo "CORRECT_TAG=1" >> $GITHUB_ENV
          fi

      - name: Test
        if: ${{ env.CORRECT_TAG == 1 }}
        run: echo Hooray
