name: Version dispatcher
on:
  push:
    tags:
    - v.*
    
env:
  CORRECT_PUSH: 0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check branch
        run: |
          if [[ "${{ github.ref }}" =~ "/ref/tags/v\.[0-9]+\.[0-9]+\.[0-9]+")]]; then
            echo YES
          else
            echo NO
          fi

      # - name: Test
      #   if: ${{ env.CORRECT_PUSH == 1 }}
      #   run: echo Hooray
