name: Version dispatcher
on:
  push:
    branches: 
    - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Extract branch nam
        shell: bash
        run: git rev-list -n 1 github.ref | git branch --contains
        id: extract_branch

      # - name: Exit if not on master branch
      #   if: endsWith(github.ref, 'master') == false
      #   run: exit -1

      - name: Run a one-line script
        run: echo Hello, world!
        
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
